name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Mod download
        run: go mod download

      - name: Verify
        run: go mod verify

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...

      - name: Race
        run: go test -race ./...

      - uses: golangci/golangci-lint-action@v6

      - name: Lint
        run: golangci-lint run

      - name: Build
        run: |
          mkdir -p bin
          go build -ldflags "-X main.version=ci -X main.gitSHA=${{ github.sha }}" -o bin/gobird ./cmd/gobird
